# Generated by Django 4.2.16 on 2024-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('citeRemitente', models.CharField(max_length=10)),
                ('referencia', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=100)),
                ('apellidosRemitente', models.CharField(max_length=30)),
                ('nombreRemitente', models.CharField(max_length=30)),
                ('cargoRemitente', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=255)),
                ('fojas', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
