# Generated by Django 4.2.16 on 2024-10-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='apellidosRemitente',
            new_name='remitente',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='citeRemitente',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='nombreRemitente',
        ),
    ]
